export function pageHtml(index=0,{missingH1=false,noindex=false,source=true}={}){
 const article=index%2===1,title=article?`Helpful evidence and practical planning guide ${index}`:`Specialist consulting service and client support ${index}`;
 return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="Explore the specific advice, approach and practical considerations on this distinct example page number ${index} for an appropriate next step.">${noindex?'<meta name="robots" content="noindex">':''}<link rel="canonical" href="https://example.com/${index?'services/page-'+index+'/':''}"><meta property="og:title" content="${title}"><meta property="og:description" content="A useful page"><meta property="og:image" content="https://example.com/image.jpg"><script type="application/ld+json">{"@type":"${article?'Article':'Service'}","name":"${title}","author":{"@type":"Person","name":"Example Author","url":"https://example.com/team/author/"},"datePublished":"2026-01-01"}</script></head><body><nav><a href="/services/">Services</a></nav><main>${missingH1?'<div class="page-title">'+title+'</div>':'<h1>'+title+'</h1>'}<h2>What this page covers</h2><p>${'Useful practical explanation about this specific subject and how readers can approach the next step. '.repeat(35)}</p><h2>How to proceed</h2><p>${'More helpful and differentiated background about the intended service and supporting evidence. '.repeat(18)}</p><a href="/services/page-2/">Related specialist service</a><a href="/blog/page-1/">Supporting practical guide</a>${source?'<a href="https://www.w3.org/WAI/tutorials/">Reference documentation and guidance</a>':''}</main></body></html>`;
}
export async function fixtureFetch(url){
 const p=url.pathname;
 if(p==='/robots.txt')return{status:200,headers:{'content-type':'text/plain'},body:'User-agent: *\nAllow: /\nSitemap: https://example.com/sitemap.xml\n'};
 if(p==='/sitemap.xml')return{status:200,headers:{'content-type':'application/xml'},body:'<urlset>'+Array.from({length:24},(_,i)=>`<url><loc>https://example.com/${i%2?'blog':'services'}/page-${i}/</loc></url>`).join('')+'</urlset>'};
 if(p==='/sitemap_index.xml')return{status:404,headers:{'content-type':'text/plain'},body:'Not found'};
 const i=Number(p.match(/page-(\d+)/)?.[1]||0);return{status:200,headers:{'content-type':'text/html'},body:pageHtml(i,{missingH1:i%2===0,noindex:i===4})};
}
