import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import {validateBrowserCapture,browserAssistRecommendations,mergeBrowserAssist} from '../src/v2/browser-assist.mjs';
import {JobManager} from '../src/v2/jobs.mjs';
const capture=(url='https://example.com/a',over={})=>({schemaVersion:'cadence-browser-assist-1',capturedAt:'2026-09-11T20:00:00Z',url,page:{title:'Example',metaDescription:'',canonical:url,robots:'',language:'en',bodyWordCount:300,headings:{h1:[],h2:['Details'],emptyCount:0},structuredDataTypes:[],images:{total:2,missingAlt:0},links:{internalPrimary:2,externalPrimary:0},authorSignals:[],openGraph:{title:'',description:''},...over}});
test('Browser Assist validates public same-origin captures and strips excess data',()=>{const c=validateBrowserCapture({...capture(),cookies:'never'},'https://example.com/');assert.equal(c.url,'https://example.com/a');assert.equal('cookies' in c,false);assert.equal(c.page.headings.h1.length,0);});
test('Browser Assist rejects cross-origin captures',()=>{assert.throws(()=>validateBrowserCapture(capture('https://other.example/a'),'https://example.com/'),/different website/);});
test('Two rendered missing-H1 captures create search-first recommendation',()=>{const r=browserAssistRecommendations([capture('https://example.com/a'),capture('https://example.com/b')]);const h=r.find(x=>x.playbook==='headings');assert.ok(h);assert.match(h.why,/Search connection/);assert.match(h.searchEffect,/Unproven/);assert.equal(h.scope,'Browser Assist sample');});
test('Browser Assist meta recommendation is snippet-focused rather than ranking claim',()=>{const r=browserAssistRecommendations([capture('https://example.com/a'),capture('https://example.com/b')]);const m=r.find(x=>x.playbook==='metadata');assert.ok(m);assert.match(m.why,/snippet/i);assert.match(m.searchEffect,/Unproven/);});
test('Merging captures labels them separately and never marks server access verified',()=>{const base={requestedUrl:'https://example.com/',finalUrl:'https://example.com/',recommendations:[],coverage:{sampleUsable:0,samplePlanned:18},warnings:[]};const r=mergeBrowserAssist(base,[capture('https://example.com/a'),capture('https://example.com/b')]);assert.equal(r.browserAssist.capturedPages,2);assert.equal(r.coverage.browserAssistPages,2);assert.match(r.browserAssist.limitations.join(' '),/does not verify initial server HTML/i);assert.ok(r.recommendations.every(x=>x.confidence.includes('browser-collected')));});
test('Job manager persists Browser Assist imports only after terminal report',async()=>{const dir=await fs.mkdtemp(path.join(os.tmpdir(),'cadence-browser-assist-'));const m=new JobManager({dataDir:dir});await m.init();try{const id='12345678-1234-1234-1234-123456789012';const j={id,owner:'o',input:{url:'https://example.com/',mode:'page'},state:'completed',createdAt:new Date().toISOString(),startedAt:null,finishedAt:new Date().toISOString(),progress:{},report:{requestedUrl:'https://example.com/',finalUrl:'https://example.com/',recommendations:[],coverage:{},warnings:[]},reviews:{},error:null};m.jobs.set(id,j);await m.save(j);const out=await m.addBrowserAssist('o',id,[capture()]);assert.equal(out.report.browserAssist.capturedPages,1);const stored=JSON.parse(await fs.readFile(path.join(dir,'jobs',id+'.json'),'utf8'));assert.equal(stored.report.browserAssist.capturedPages,1);}finally{await m.close();await fs.rm(dir,{recursive:true,force:true});}});
test('Browser Assist keeps blocked link checks unverified and can recommend real broken destinations',()=>{const a=capture('https://example.com/a',{links:{internalPrimary:3,externalPrimary:0,checked:[{url:'https://example.com/gone',finalUrl:'https://example.com/gone',status:404,redirected:false,accessRestricted:false},{url:'https://example.com/blocked',finalUrl:'https://example.com/blocked',status:403,redirected:false,accessRestricted:true}]}});const clean=validateBrowserCapture(a,'https://example.com/');assert.equal(clean.page.links.checked.length,2);const r=browserAssistRecommendations([clean]);const b=r.find(x=>x.playbook==='broken');assert.ok(b);assert.match(b.talk,/dead ends/i);assert.doesNotMatch(b.evidence.map(e=>e.value).join(' '),/blocked/);});
test('Merged Browser Assist reports bounded link-health counts',()=>{const a=capture('https://example.com/a',{links:{internalPrimary:2,externalPrimary:0,checked:[{url:'https://example.com/live',finalUrl:'https://example.com/new',status:200,redirected:true,accessRestricted:false},{url:'https://example.com/nope',finalUrl:'https://example.com/nope',status:null,redirected:false,accessRestricted:false,error:'Timed out'}]}});const r=mergeBrowserAssist({requestedUrl:'https://example.com/',finalUrl:'https://example.com/',recommendations:[],coverage:{},warnings:[]},[a]);assert.equal(r.browserAssist.linkHealth.checked,2);assert.equal(r.browserAssist.linkHealth.redirected,1);assert.equal(r.browserAssist.linkHealth.unverified,1);});


test('Browser Assist can surface a multi-signal content freshness review without calling age alone a problem',()=>{
 const capture={schemaVersion:'cadence-browser-assist-1',capturedAt:'2026-09-12T00:00:00Z',url:'https://example.com/blog/guide-2022/',page:{title:'Example Guide 2022',metaDescription:'Updated for 2022',canonical:'https://example.com/blog/guide-2022/',robots:'',language:'en',bodyWordCount:900,headings:{h1:['Example Guide'],h2:[],emptyCount:0},structuredDataTypes:['BlogPosting'],images:{total:1,missingAlt:0},links:{internalPrimary:2,externalPrimary:1,checked:[]},freshness:{datePublished:['2022-01-01'],dateModified:[],titleYears:[2022],metaDescriptionYears:[2022],bodyYears:[2020,2021,2022],sourceLinkYears:[2020]},authorSignals:[],openGraph:{}}};
 const clean=validateBrowserCapture(capture,'https://example.com/');
 const recs=browserAssistRecommendations([clean]);
 assert.ok(recs.some(r=>r.playbook==='freshness'));
 assert.match(recs.find(r=>r.playbook==='freshness').caveat,/cannot prove content decay/i);
});
