const button=document.getElementById('capture'),status=document.getElementById('status');
function capturePage(){
 const text=(el)=>el?.textContent?.replace(/\s+/g,' ').trim()||'';
 const abs=(v)=>{try{return new URL(v,location.href).href}catch{return null}};
 const meta=(name)=>document.querySelector(`meta[name="${name}"]`)?.content?.trim()||'';
 const prop=(name)=>document.querySelector(`meta[property="${name}"]`)?.content?.trim()||'';
 const primary=document.querySelector('main,article,[role="main"]')||document.body;
 const internal=[...primary.querySelectorAll('a[href]')].filter(a=>{try{return new URL(a.href).origin===location.origin}catch{return false}}).length;
 const external=[...primary.querySelectorAll('a[href]')].filter(a=>{try{return /^https?:/.test(new URL(a.href).protocol)&&new URL(a.href).origin!==location.origin}catch{return false}}).length;
 const types=[];for(const s of document.querySelectorAll('script[type="application/ld+json"]')){try{const root=JSON.parse(s.textContent);const walk=o=>{if(!o||typeof o!=='object')return;if(Array.isArray(o)){o.forEach(walk);return;}if(o['@type']){(Array.isArray(o['@type'])?o['@type']:[o['@type']]).forEach(t=>types.push(String(t)));}Object.values(o).forEach(walk);};walk(root);}catch{}}
 const imgs=[...document.images];
 const author=[...document.querySelectorAll('[rel="author"],.author,.byline,[class*="author" i]')].map(text).filter(Boolean).slice(0,10);
 return{schemaVersion:'cadence-browser-assist-1',capturedAt:new Date().toISOString(),url:location.href,page:{title:document.title||'',metaDescription:meta('description'),canonical:abs(document.querySelector('link[rel="canonical"]')?.href||''),robots:meta('robots'),language:document.documentElement.lang||'',bodyWordCount:(text(primary).match(/\b[\p{L}\p{N}][\p{L}\p{N}'’-]*\b/gu)||[]).length,headings:{h1:[...primary.querySelectorAll('h1')].map(text).filter(Boolean),h2:[...primary.querySelectorAll('h2')].map(text).filter(Boolean),emptyCount:[...primary.querySelectorAll('h1,h2,h3,h4,h5,h6')].filter(h=>!text(h)).length},structuredDataTypes:[...new Set(types)],images:{total:imgs.length,missingAlt:imgs.filter(i=>!i.hasAttribute('alt')).length},links:{internalPrimary:internal,externalPrimary:external},authorSignals:author,openGraph:{title:prop('og:title'),description:prop('og:description')}}};
}
button.addEventListener('click',async()=>{button.disabled=true;status.textContent='Capturing…';try{const [tab]=await chrome.tabs.query({active:true,currentWindow:true});if(!tab?.id||!/^https?:/.test(tab.url||''))throw new Error('Open a public http(s) page first.');const [{result}]=await chrome.scripting.executeScript({target:{tabId:tab.id},func:capturePage});const name=`cadence-browser-assist-${new URL(result.url).hostname}-${Date.now()}.json`;const blob=new Blob([JSON.stringify(result,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob);await chrome.downloads.download({url,filename:name,saveAs:false});setTimeout(()=>URL.revokeObjectURL(url),1000);status.textContent='Capture saved to Downloads. Import it into the V2 audit.';}catch(e){status.textContent=e.message||'Capture failed.';}finally{button.disabled=false;}});
