export function recordingBrief(report,reviews={}){
 const recs=report?.recommendations||[];
 const selected=recs.filter(r=>reviews[r.id]?.decision==='use'&&reviews[r.id]?.verified===true);
 const investigate=recs.filter(r=>reviews[r.id]?.decision==='investigate');
 const anyReviewed=recs.some(r=>reviews[r.id]?.decision&&reviews[r.id].decision!=='unreviewed');
 const suggestions=anyReviewed?[]:recs;
 const main=selected.length?selected:suggestions;
 const c=report.coverage||{},q=report.qa||{};
 const lines=['CADENCE SEARCH | SALES AUDIT BRIEF',`URL: ${report.finalUrl||report.requestedUrl}`,`Coverage: ${c.sampleUsable||0}/${c.samplePlanned??c.sampleAttempted??0} usable sampled pages; ${c.relationshipPages||0}/${c.relationshipPlanned??c.relationshipPages??0} usable relationship pages; ${c.renderedPageCount||0} entry-page browser render.`,`Scan: ${report.status}. This is a sample, not a sitewide clearance.`,`On-page QA: ${q.issueObservations||0} implementation observations; ${q.reviewObservations||0} review observations.`,...((report.warnings||[]).length?['Coverage gaps: '+report.warnings.map(w=>w.component+': '+w.message).join(' | ')]:[]),...(report.searchAccess?[`Search & AI policy: ${report.searchAccess.summary.entries} agents/controls evaluated across ${report.searchAccess.pageCount} URL paths; ${report.searchAccess.summary.searchRestricted} search entries have disallowed paths; ${report.searchAccess.summary.searchUnknown} search entries have unknown outcomes. Actual provider access is not verified.`, `Training-only restrictions are policy choices, not automatic search problems. Mixed-use controls are reviewed separately.`]:[]),'','OPENING','I reviewed a bounded sample for organic search visibility and AI-assisted discovery. The same technical and content foundations often support both, but this brief separates documented AI relevance from unproven citation or ranking claims.','',selected.length?'SELECTED AFTER REVIEW':suggestions.length?'UNREVIEWED SUGGESTIONS - NOT CLIENT-READY':'NO RECOMMENDATIONS SELECTED'];
 main.forEach((r,i)=>{lines.push('',`${i+1}. ${r.title}`,`What we observed: ${r.observation}`,`Why it matters for search visibility: ${r.why}`,...(r.aiWhy?[`AI search relevance (${r.aiLevel||'context'}): ${r.aiWhy}`,`AI effect - supported vs. unproven: ${r.aiEffect||'Provider-specific impact is not established.'}`]:[]),'Cadence search approach: '+r.solution.join(' '),`Search success check: ${r.success}`,`Talk track: ${r.talk}`,...(r.aiTalk?[`AI angle for the conversation: ${r.aiTalk}`]:[]),`Expected search effect - supported vs. unproven: ${r.searchEffect||r.caveat}`,...(r.userNote?[`Secondary user benefit: ${r.userNote.replace(/^Secondary benefit:\s*/i,'')}`]:[]),`Qualification: ${r.caveat}`);const urls=[...new Set(r.evidence.map(e=>e.url).filter(Boolean))].slice(0,3);if(urls.length)lines.push('Examples: '+urls.join(' | '));if(reviews[r.id]?.note)lines.push('Auditor note: '+reviews[r.id].note);});
 if(investigate.length){lines.push('','NEEDS INVESTIGATION');for(const r of investigate)lines.push('',r.title,'Verify: '+r.verify,'Qualification: '+r.caveat);}
 lines.push('','CLOSING',main.length?'We would verify the examples, agree the priority pages, implement the appropriate changes and test the search and AI-discovery outcomes that can actually be measured. These are proposed improvements, not a promise of rankings, AI citations or leads.':'The scan does not supply a client-ready recommendation yet. Complete the evidence review or investigate the coverage gaps before recording.');
 return lines.join('\n');
}
