import {AI_RELEVANCE} from './playbooks.mjs';
const MAX_CAPTURES=10;
const text=(v,n=500)=>String(v??'').trim().slice(0,n);
const arr=(v,max=50)=>Array.isArray(v)?v.slice(0,max):[];
const safeUrl=v=>{try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;return u.href;}catch{return null;}};
const originOf=v=>{try{return new URL(v).origin;}catch{return null;}};
export function validateBrowserCapture(value,reportUrl){
 if(!value||value.schemaVersion!=='cadence-browser-assist-1')throw Object.assign(new Error('This is not a Cadence Browser Assist capture.'),{status:400,code:'BROWSER_CAPTURE_SCHEMA'});
 const url=safeUrl(value.url);if(!url)throw Object.assign(new Error('Browser Assist capture has an invalid public URL.'),{status:400,code:'BROWSER_CAPTURE_URL'});
 if(reportUrl&&originOf(url)!==originOf(reportUrl))throw Object.assign(new Error('This capture is from a different website than the current audit.'),{status:400,code:'BROWSER_CAPTURE_ORIGIN'});
 const p=value.page||{},headings=p.headings||{},images=p.images||{},links=p.links||{};
 return{schemaVersion:'cadence-browser-assist-1',capturedAt:text(value.capturedAt,60)||new Date().toISOString(),url,
  page:{title:text(p.title,300),metaDescription:text(p.metaDescription,600),canonical:safeUrl(p.canonical),robots:text(p.robots,300),language:text(p.language,30),bodyWordCount:Number.isFinite(+p.bodyWordCount)?Math.max(0,Math.min(200000,+p.bodyWordCount)):0,
   headings:{h1:arr(headings.h1,10).map(x=>text(x,300)).filter(Boolean),h2:arr(headings.h2,30).map(x=>text(x,300)).filter(Boolean),emptyCount:Math.max(0,Math.min(100,Number(headings.emptyCount)||0))},
   structuredDataTypes:[...new Set(arr(p.structuredDataTypes,40).map(x=>text(x,100)).filter(Boolean))],
   images:{total:Math.max(0,Math.min(5000,Number(images.total)||0)),missingAlt:Math.max(0,Math.min(5000,Number(images.missingAlt)||0))},
   links:{internalPrimary:Math.max(0,Math.min(5000,Number(links.internalPrimary)||0)),externalPrimary:Math.max(0,Math.min(5000,Number(links.externalPrimary)||0)),checked:arr(links.checked,15).map(item=>{const target=safeUrl(item?.url),finalUrl=safeUrl(item?.finalUrl)||target;if(!target||originOf(target)!==originOf(url))return null;return{url:target,finalUrl,status:Number.isFinite(+item?.status)?Math.max(0,Math.min(599,+item.status)):null,redirected:!!item?.redirected,accessRestricted:!!item?.accessRestricted,error:text(item?.error,120)||null};}).filter(Boolean)},
   authorSignals:arr(p.authorSignals,10).map(x=>text(x,200)).filter(Boolean),openGraph:{title:text(p.openGraph?.title,300),description:text(p.openGraph?.description,600)}}};
}
const evidence=(captures,label,predicate,formatter)=>captures.filter(predicate).slice(0,10).map(c=>({label,value:formatter(c),url:c.url}));
function rec({id,playbook,title,theme,observation,why,solution,success,searchEffect,caveat,effort,talk,source,evidence}){const ai=AI_RELEVANCE[playbook]||{};return{id:'browser:'+id,playbook,title,theme,scope:'Browser Assist sample',observation,why,solution,success,verify:solution[0],searchEffect,aiLevel:ai.level||'',aiWhy:ai.why||'',aiEffect:ai.effect||'',aiSource:ai.source||'',aiTalk:ai.talk||'',caveat,effort,priority:'Planned review',confidence:'Observed in browser-collected public-page output; server response and crawler access are not verified',talk,source,evidence,review:'unreviewed',originalFinding:{id:'browser-'+id,title,category:'browser-assist',confidence:'confirmed'}};}
export function browserAssistRecommendations(captures=[]){
 const n=captures.length;if(!n)return[];const out=[];
 const linkChecks=captures.flatMap(c=>(c.page.links?.checked||[]).map(x=>({...x,source:c.url})));const brokenLinks=linkChecks.filter(x=>!x.accessRestricted&&!x.error&&Number(x.status)>=400&&!([401,403,407,429].includes(Number(x.status))));
 if(brokenLinks.length)out.push(rec({id:'broken-links',playbook:'broken',title:'Fix broken links and pages',theme:'Technical',observation:`Browser Assist found ${brokenLinks.length} internal destination${brokenLinks.length===1?'':'s'} returning an error response across the captured public pages.`,why:'Search connection: internal links help search engines discover and revisit important pages. A real error destination creates a dead end in that path.',solution:['Open the affected source and destination to confirm the error is persistent.','Restore the intended page, update the source link, or redirect the old URL to the correct replacement when the content genuinely moved.','Recheck the link from the browser and keep crawler-access conclusions separate unless provider access is verified.'],success:'The reviewed internal links reach the intended live destination without a confirmed error response.',searchEffect:'Supported after confirmation: removing a real error from an internal crawl path. Unproven: that Google or an AI provider encountered the same error or that it caused ranking loss.',caveat:'Browser Assist checks a small same-origin link sample from the public page you opened. Access-denied responses are not classified as broken.',effort:'Usually a link, redirect or page-restoration change.',talk:'Some links lead to pages that no longer work. We’d fix the link, restore the page, or redirect it to the right replacement so search engines and AI systems do not hit avoidable dead ends.',source:'https://developers.google.com/search/docs/crawling-indexing/http-network-errors',evidence:brokenLinks.slice(0,8).map(x=>({label:`HTTP ${x.status}`,value:`${x.source} -> ${x.url}`,url:x.url}))}));
 const noH1=captures.filter(c=>!c.page.headings.h1.length);
 if(noH1.length>=Math.min(2,n))out.push(rec({id:'missing-h1',playbook:'headings',title:"Strengthen each page's main search topic",theme:'On-page',observation:`Browser Assist did not detect an H1 in the rendered public page for ${noH1.length} of ${n} captured prospect pages.`,why:'Search connection: a descriptive main heading can reinforce the page topic and can be one of the signals Google uses when generating title links. The absence of an H1 alone does not prove ranking loss.',solution:['Compare each visible page title, title tag and rendered H1 and confirm the page clearly identifies the service or topic it should be found for.','Where the page title is unclear or not marked as the main heading, correct the content and template together rather than inserting a tag only to satisfy the audit.','Recheck the rendered page after the change and evaluate search performance separately after recrawling.'],success:'The captured priority pages expose a clear, descriptive main heading aligned with their intended search topic.',searchEffect:'Supported: clearer rendered topic/title signals. Unproven: that the missing H1 caused lost rankings, traffic or leads.',caveat:'Browser Assist observes the rendered page you opened. It does not establish what a crawler received in the initial server response.',effort:'Template/content review and QA.',talk:'Each page should make its main topic obvious. We’d make sure the primary service or subject is clearly stated in the main heading so search engines have a cleaner understanding of what the page is about.',source:'https://developers.google.com/search/docs/appearance/title-link',evidence:evidence(captures,'H1',c=>!c.page.headings.h1.length,()=> 'No H1 detected in rendered public page')}));
 const noMeta=captures.filter(c=>!c.page.metaDescription);
 if(noMeta.length>=Math.min(2,n))out.push(rec({id:'missing-meta',playbook:'metadata',title:'Improve the message searchers may see before the click',theme:'Search appearance',observation:`Browser Assist did not detect a meta description on ${noMeta.length} of ${n} captured pages.`,why:'Search connection: Google may use a page meta description when it better describes the page than extracted on-page text. This is primarily a search-snippet messaging opportunity, not a direct ranking requirement.',solution:['Review the search intent and value proposition of each affected page.','Write concise, page-specific descriptions that accurately summarize the page and give qualified searchers a reason to click.','Recheck the rendered metadata and review actual Google snippets after recrawling; Google may still choose other page text.'],success:'Priority pages expose accurate, distinct meta descriptions that support their search-result messaging.',searchEffect:'Supported: stronger candidate snippet text. Unproven: higher rankings or guaranteed use of the supplied description.',caveat:'Google can generate snippets from page content instead of the meta description.',effort:'Content/template update and SERP QA.',talk:'The description is the page’s short sales message in search. We’d make it clear, specific and relevant so the result does a better job of explaining why someone should click.',source:'https://developers.google.com/search/docs/appearance/snippet',evidence:evidence(captures,'Meta description',c=>!c.page.metaDescription,()=> 'No meta description detected in rendered public page')}));
 const noTitle=captures.filter(c=>!c.page.title);
 if(noTitle.length)out.push(rec({id:'missing-title',playbook:'titles',title:'Restore a primary search-result title signal',theme:'Search appearance',observation:`Browser Assist did not detect a document title on ${noTitle.length} of ${n} captured pages.`,why:'Search connection: the HTML title element is a primary source Google can use for title links in search results.',solution:['Confirm the affected pages truly lack a useful title element in the rendered document.','Write unique descriptive titles aligned with each page purpose and important search topic.','Verify the output and monitor how Google presents the title after recrawling.'],success:'Each priority page exposes a descriptive, unique document title aligned with the page topic.',searchEffect:'Supported: restoring a core title-link input. Unproven: a particular ranking change.',caveat:'Google can generate title links from multiple page signals and may rewrite supplied titles.',effort:'Content/template change and QA.',talk:'The page title helps search engines and searchers understand what a result is about before the click. We’d make each important page specific and easy to distinguish so it has a clearer search identity.',source:'https://developers.google.com/search/docs/appearance/title-link',evidence:evidence(captures,'Title',c=>!c.page.title,()=> 'No document title detected')}));
 return out.slice(0,5);
}
export function mergeBrowserAssist(report,captures){
 const baseUrl=report.finalUrl||report.requestedUrl;const clean=[];const seen=new Set();for(const c of captures.slice(0,MAX_CAPTURES)){const x=validateBrowserCapture(c,baseUrl);if(!seen.has(x.url)){seen.add(x.url);clean.push(x);}}
 const browserRecs=browserAssistRecommendations(clean),existing=(report.recommendations||[]).filter(r=>!String(r.id).startsWith('browser:'));
 const merged=[...browserRecs,...existing].slice(0,5);
 const browserChecks=clean.flatMap(c=>(c.page.links?.checked||[]).map(x=>({...x,source:c.url})));const browserLinkHealth={checked:browserChecks.length,broken:browserChecks.filter(x=>!x.accessRestricted&&!x.error&&Number(x.status)>=400&&!([401,403,407,429].includes(Number(x.status)))).length,redirected:browserChecks.filter(x=>x.redirected&&Number(x.status)<400).length,unverified:browserChecks.filter(x=>x.accessRestricted||x.error||x.status===null).length};
 return{...report,browserAssist:{capturedPages:clean.length,pages:clean,linkHealth:browserLinkHealth,limitations:['Browser Assist reflects the rendered public pages opened manually in Chrome.','It does not verify initial server HTML, HTTP response behavior, robots enforcement, firewall behavior or real search/AI crawler access.','Only deliberately captured public pages are included; form values, cookies and credentials are not collected by the extension.']},recommendations:merged,coverage:{...(report.coverage||{}),browserAssistPages:clean.length},warnings:[...(report.warnings||[]),...(clean.length?[{component:'Browser Assist',message:`${clean.length} public page capture(s) were added as rendered-page evidence. Server-only and crawler-access checks remain separate.`}]:[])]};
}
export {MAX_CAPTURES};
