const MAX_CAPTURES=10;
const text=(v,n=500)=>String(v??'').trim().slice(0,n);
const arr=(v,max=50)=>Array.isArray(v)?v.slice(0,max):[];
const safeUrl=v=>{try{const u=new URL(v);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return null;return u.href;}catch{return null;}};
const originOf=v=>{try{return new URL(v).origin;}catch{return null;}};
export function validateBrowserCapture(value,reportUrl){
 if(!value||value.schemaVersion!=='cadence-browser-assist-1')throw Object.assign(new Error('This is not a Cadence Browser Assist capture.'),{status:400,code:'BROWSER_CAPTURE_SCHEMA'});
 const url=safeUrl(value.url);if(!url)throw Object.assign(new Error('Browser Assist capture has an invalid public URL.'),{status:400,code:'BROWSER_CAPTURE_URL'});
 if(reportUrl&&originOf(url)!==originOf(reportUrl))throw Object.assign(new Error('This capture is from a different website than the current audit.'),{status:400,code:'BROWSER_CAPTURE_ORIGIN'});
 const p=value.page||{},headings=p.headings||{},images=p.images||{},links=p.links||{};
 return{schemaVersion:'cadence-browser-assist-1',capturedAt:text(value.capturedAt,60)||new Date().toISOString(),url,
  page:{title:text(p.title,300),metaDescription:text(p.metaDescription,600),canonical:safeUrl(p.canonical),robots:text(p.robots,300),language:text(p.language,30),bodyWordCount:Number.isFinite(+p.bodyWordCount)?Math.max(0,Math.min(200000,+p.bodyWordCount)):0,
   headings:{h1:arr(headings.h1,10).map(x=>text(x,300)).filter(Boolean),h2:arr(headings.h2,30).map(x=>text(x,300)).filter(Boolean),emptyCount:Math.max(0,Math.min(100,Number(headings.emptyCount)||0))},
   structuredDataTypes:[...new Set(arr(p.structuredDataTypes,40).map(x=>text(x,100)).filter(Boolean))],
   images:{total:Math.max(0,Math.min(5000,Number(images.total)||0)),missingAlt:Math.max(0,Math.min(5000,Number(images.missingAlt)||0))},
   links:{internalPrimary:Math.max(0,Math.min(5000,Number(links.internalPrimary)||0)),externalPrimary:Math.max(0,Math.min(5000,Number(links.externalPrimary)||0))},
   authorSignals:arr(p.authorSignals,10).map(x=>text(x,200)).filter(Boolean),openGraph:{title:text(p.openGraph?.title,300),description:text(p.openGraph?.description,600)}}};
}
const evidence=(captures,label,predicate,formatter)=>captures.filter(predicate).slice(0,10).map(c=>({label,value:formatter(c),url:c.url}));
function rec({id,playbook,title,theme,observation,why,solution,success,searchEffect,caveat,effort,talk,source,evidence}){return{id:'browser:'+id,playbook,title,theme,scope:'Browser Assist sample',observation,why,solution,success,verify:solution[0],searchEffect,caveat,effort,priority:'Planned review',confidence:'Observed in browser-collected public-page output; server response and crawler access are not verified',talk,source,evidence,review:'unreviewed',originalFinding:{id:'browser-'+id,title,category:'browser-assist',confidence:'confirmed'}};}
export function browserAssistRecommendations(captures=[]){
 const n=captures.length;if(!n)return[];const out=[];
 const noH1=captures.filter(c=>!c.page.headings.h1.length);
 if(noH1.length>=Math.min(2,n))out.push(rec({id:'missing-h1',playbook:'headings',title:"Strengthen each page's main search topic",theme:'On-page',observation:`Browser Assist did not detect an H1 in the rendered public page for ${noH1.length} of ${n} captured prospect pages.`,why:'Search connection: a descriptive main heading can reinforce the page topic and can be one of the signals Google uses when generating title links. The absence of an H1 alone does not prove ranking loss.',solution:['Compare each visible page title, title tag and rendered H1 and confirm the page clearly identifies the service or topic it should be found for.','Where the page title is unclear or not marked as the main heading, correct the content and template together rather than inserting a tag only to satisfy the audit.','Recheck the rendered page after the change and evaluate search performance separately after recrawling.'],success:'The captured priority pages expose a clear, descriptive main heading aligned with their intended search topic.',searchEffect:'Supported: clearer rendered topic/title signals. Unproven: that the missing H1 caused lost rankings, traffic or leads.',caveat:'Browser Assist observes the rendered page you opened. It does not establish what a crawler received in the initial server response.',effort:'Template/content review and QA.',talk:`We opened ${n} public pages directly in a browser and ${noH1.length} did not expose a main H1. We would make sure those pages clearly identify the service or topic they are meant to rank for, fix the template where needed, and verify the rendered output.`,source:'https://developers.google.com/search/docs/appearance/title-link',evidence:evidence(captures,'H1',c=>!c.page.headings.h1.length,()=> 'No H1 detected in rendered public page')}));
 const noMeta=captures.filter(c=>!c.page.metaDescription);
 if(noMeta.length>=Math.min(2,n))out.push(rec({id:'missing-meta',playbook:'metadata',title:'Improve the message searchers may see before the click',theme:'Search appearance',observation:`Browser Assist did not detect a meta description on ${noMeta.length} of ${n} captured pages.`,why:'Search connection: Google may use a page meta description when it better describes the page than extracted on-page text. This is primarily a search-snippet messaging opportunity, not a direct ranking requirement.',solution:['Review the search intent and value proposition of each affected page.','Write concise, page-specific descriptions that accurately summarize the page and give qualified searchers a reason to click.','Recheck the rendered metadata and review actual Google snippets after recrawling; Google may still choose other page text.'],success:'Priority pages expose accurate, distinct meta descriptions that support their search-result messaging.',searchEffect:'Supported: stronger candidate snippet text. Unproven: higher rankings or guaranteed use of the supplied description.',caveat:'Google can generate snippets from page content instead of the meta description.',effort:'Content/template update and SERP QA.',talk:`Several public pages we captured do not provide a meta description. We would improve the search-result messaging on those pages and then verify how Google actually presents them.`,source:'https://developers.google.com/search/docs/appearance/snippet',evidence:evidence(captures,'Meta description',c=>!c.page.metaDescription,()=> 'No meta description detected in rendered public page')}));
 const noTitle=captures.filter(c=>!c.page.title);
 if(noTitle.length)out.push(rec({id:'missing-title',playbook:'titles',title:'Restore a primary search-result title signal',theme:'Search appearance',observation:`Browser Assist did not detect a document title on ${noTitle.length} of ${n} captured pages.`,why:'Search connection: the HTML title element is a primary source Google can use for title links in search results.',solution:['Confirm the affected pages truly lack a useful title element in the rendered document.','Write unique descriptive titles aligned with each page purpose and important search topic.','Verify the output and monitor how Google presents the title after recrawling.'],success:'Each priority page exposes a descriptive, unique document title aligned with the page topic.',searchEffect:'Supported: restoring a core title-link input. Unproven: a particular ranking change.',caveat:'Google can generate title links from multiple page signals and may rewrite supplied titles.',effort:'Content/template change and QA.',talk:'We found a page without a document title in the public browser view. We would restore that core search-result signal and verify the rendered output.',source:'https://developers.google.com/search/docs/appearance/title-link',evidence:evidence(captures,'Title',c=>!c.page.title,()=> 'No document title detected')}));
 return out.slice(0,5);
}
export function mergeBrowserAssist(report,captures){
 const baseUrl=report.finalUrl||report.requestedUrl;const clean=[];const seen=new Set();for(const c of captures.slice(0,MAX_CAPTURES)){const x=validateBrowserCapture(c,baseUrl);if(!seen.has(x.url)){seen.add(x.url);clean.push(x);}}
 const browserRecs=browserAssistRecommendations(clean),existing=(report.recommendations||[]).filter(r=>!String(r.id).startsWith('browser:'));
 const merged=[...browserRecs,...existing].slice(0,5);
 return{...report,browserAssist:{capturedPages:clean.length,pages:clean,limitations:['Browser Assist reflects the rendered public pages opened manually in Chrome.','It does not verify initial server HTML, HTTP response behavior, robots enforcement, firewall behavior or real search/AI crawler access.','Only deliberately captured public pages are included; form values, cookies and credentials are not collected by the extension.']},recommendations:merged,coverage:{...(report.coverage||{}),browserAssistPages:clean.length},warnings:[...(report.warnings||[]),...(clean.length?[{component:'Browser Assist',message:`${clean.length} public page capture(s) were added as rendered-page evidence. Server-only and crawler-access checks remain separate.`}]:[])]};
}
export {MAX_CAPTURES};
